# Imagen base
FROM python:3.9-slim

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar archivo local al contenedor
COPY app.py .

# Comando para ejecutar la aplicación
CMD ["python", "app.py"]
